services:
  - type: web
    name: wheelchair-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
